import React from "react";
import {
  ApiOutlined,
  ApartmentOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  CalendarOutlined,
  CarOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  ClusterOutlined,
  ColumnHeightOutlined,
  ControlOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  DeploymentUnitOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  LineChartOutlined,
  LinkOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  NotificationOutlined,
  ProfileOutlined,
  QrcodeOutlined,
  RiseOutlined,
  SafetyCertificateOutlined,
  SettingOutlined,
  ShopOutlined,
  SolutionOutlined,
  SyncOutlined,
  TagsOutlined,
  TeamOutlined,
  ToolOutlined,
  UnorderedListOutlined,
  UserOutlined,
  WalletOutlined,
} from "@ant-design/icons";

const icon = (Icon: any) => React.createElement(Icon);

const ICON_MAP: Record<string, React.ReactNode> = {
  dashboard: icon(DashboardOutlined),
  operations: icon(AppstoreOutlined),
  approval: icon(CheckSquareOutlined),
  Dashboard: icon(AppstoreOutlined),
  org: icon(ApartmentOutlined),
  organisations: icon(ApartmentOutlined),
  org_mandi: icon(DeploymentUnitOutlined),
  Link: icon(LinkOutlined),
  mandi: icon(ShopOutlined),
  commodities: icon(TagsOutlined),
  products: icon(InboxOutlined),
  mandi_products: icon(InboxOutlined),
  admin_users: icon(SafetyCertificateOutlined),
  farmers: icon(UserOutlined),
  traders: icon(TeamOutlined),
  trader_approvals: icon(CheckSquareOutlined),
  QrCode: icon(QrcodeOutlined),
  device: icon(MobileOutlined),
  gate_devices: icon(ApiOutlined),
  gate_device_configs: icon(ToolOutlined),
  gate_entry_reasons: icon(FileTextOutlined),
  gate_movements: icon(LineChartOutlined),
  gate_tokens: icon(IdcardOutlined),
  vehicle: icon(CarOutlined),
  auction_methods: icon(AuditOutlined),
  auction_rounds: icon(SyncOutlined),
  auction_policies: icon(SolutionOutlined),
  auction_sessions: icon(CalendarOutlined),
  auction_lots: icon(InboxOutlined),
  auction_results: icon(FileDoneOutlined),
  fees: icon(FileTextOutlined),
  prices: icon(RiseOutlined),
  mandi_prices: icon(DollarOutlined),
  market_prices: icon(LineChartOutlined),
  transport: icon(CarOutlined),
  reports: icon(BarChartOutlined),
  security: icon(SafetyCertificateOutlined),
  toggle: icon(ControlOutlined),
  mandi_coverage: icon(EnvironmentOutlined),
  mandi_facilities: icon(HomeOutlined),
  mandi_gates: icon(HomeOutlined),
  mandi_hours: icon(ClockCircleOutlined),
  pre_market: icon(UnorderedListOutlined),
  weighment_tickets: icon(ColumnHeightOutlined),
  payment_gateway: icon(SettingOutlined),
};

const RESOURCE_ICON_MAP: Record<string, React.ReactNode> = {
  "dashboard.menu": icon(DashboardOutlined),
  "mandi_operations.menu": icon(AppstoreOutlined),
  "organisations.menu": icon(ApartmentOutlined),
  "admin_users.menu": icon(SafetyCertificateOutlined),
  "org_mandi_mappings.menu": icon(DeploymentUnitOutlined),
  "mandis.menu": icon(ShopOutlined),
  "commodities_masters.menu": icon(TagsOutlined),
  "commodity_products_masters.menu": icon(InboxOutlined),
  "mandi_commodity_products_masters.menu": icon(InboxOutlined),
  "mandi_facilities.menu": icon(HomeOutlined),
  "mandi_hours.menu": icon(ClockCircleOutlined),
  "gate_entry_reasons_masters.menu": icon(FileTextOutlined),
  "gate_vehicle_types_masters.menu": icon(CarOutlined),
  "mandi_gates.menu": icon(HomeOutlined),
  "gate_devices.menu": icon(MobileOutlined),
  "cm_gate_devices.menu": icon(ApiOutlined),
  "gate_device_configs.menu": icon(ToolOutlined),
  "gate_entry_tokens.menu": icon(QrcodeOutlined),
  "pre_market_listings.menu": icon(UnorderedListOutlined),
  "stall_fees.menu": icon(FileTextOutlined),
  "market_prices.menu": icon(LineChartOutlined),
  "mandi_price_policies.menu": icon(DollarOutlined),
  "mandi_settings.menu": icon(SettingOutlined),
  "transport_intents.menu": icon(CarOutlined),
  "mandi_associations.menu": icon(LinkOutlined),
  "gate_movements_log.view": icon(LineChartOutlined),
  "weighment_tickets.view": icon(ColumnHeightOutlined),
  "auction_methods_masters.menu": icon(AuditOutlined),
  "auction_rounds_masters.menu": icon(SyncOutlined),
  "cm_mandi_auction_policies.menu": icon(SolutionOutlined),
  "auction_policy_settings.menu": icon(ControlOutlined),
  "auction_sessions.menu": icon(CalendarOutlined),
  "lots.menu": icon(UnorderedListOutlined),
  "auction_lots.menu": icon(InboxOutlined),
  "auction_results.menu": icon(FileDoneOutlined),
  "trader_approvals.menu": icon(CheckSquareOutlined),
  "mandi_approvals.menu": icon(CheckSquareOutlined),
  "mandi_staff.menu": icon(TeamOutlined),
  "mandi_staff.list": icon(TeamOutlined),
  "mandi_reports.menu": icon(BarChartOutlined),
  "mandi_management.menu": icon(SettingOutlined),
  "traders.menu": icon(TeamOutlined),
  "farmers.menu": icon(UserOutlined),
  "commodity_fees.menu": icon(MoneyCollectOutlined),
  "custom_fees.menu": icon(ControlOutlined),
  "mandi_payment_settings.menu": icon(SettingOutlined),
  "org_payment_settings.menu": icon(BankOutlined),
  "payment_models.menu": icon(ClusterOutlined),
  "payment_modes.menu": icon(CreditCardOutlined),
  "payment_gateway_configs.menu": icon(WalletOutlined),
  "payment_gateway_settings.menu": icon(SettingOutlined),
  "payment_payout_settings.menu": icon(DollarOutlined),
  "settlement_charge_settings.menu": icon(MoneyCollectOutlined),
  "payment_vendor_accounts.menu": icon(ProfileOutlined),
  "payments_log.menu": icon(FileTextOutlined),
  "role_custom_fees.menu": icon(IdcardOutlined),
  "settlements.menu": icon(BankOutlined),
  "subscription_invoices.menu": icon(FileDoneOutlined),
  "subscriptions.menu": icon(ProfileOutlined),
  "reports.menu": icon(BarChartOutlined),
  "mandi_coverage.menu": icon(EnvironmentOutlined),
  "mandi_prices.menu": icon(DollarOutlined),
  "system_security.menu": icon(SafetyCertificateOutlined),
  "platform_control_center.menu": icon(ClusterOutlined),
  "notification_templates.menu": icon(NotificationOutlined),
  "user_roles.menu": icon(TeamOutlined),
  "resource_registry.menu": icon(AppstoreOutlined),
  "security_2fa.menu": icon(MobileOutlined),
  "security_switches.menu": icon(ControlOutlined),
  "stepup_policy.menu": icon(SafetyCertificateOutlined),
  "role_policies.menu": icon(SolutionOutlined),
  "workflow_policies.menu": icon(SolutionOutlined),
  "mobile_dashboard.menu": icon(MobileOutlined),
  "capacity_control.menu": icon(BarChartOutlined),
  "notifications.menu": icon(BellOutlined),
};

export function resolveMenuIcon(iconKey?: string | null, resourceKey?: string | null): React.ReactNode | undefined {
  if (resourceKey && RESOURCE_ICON_MAP[resourceKey]) return RESOURCE_ICON_MAP[resourceKey];
  if (iconKey && ICON_MAP[iconKey]) return ICON_MAP[iconKey];
  return icon(AppstoreOutlined);
}
