export type FrozenMenuItem = {
  category: string;
  resource_key: string;
  menu_name: string;
  name_source: string;
  i18n_key: string;
  route: string;
  icon_key: string;
  order: number | null;
  metadata_group: string;
  is_active: boolean | string | null;
};

export const MENU_FREEZE: FrozenMenuItem[] = [
  {
    "category": "Auction",
    "resource_key": "auction_methods_masters.menu",
    "menu_name": "Auction Methods",
    "name_source": "screen",
    "i18n_key": "menu.auctionMethods",
    "route": "/auction-methods",
    "icon_key": "auction_methods",
    "order": 70,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Auction",
    "resource_key": "auction_rounds_masters.menu",
    "menu_name": "Auction Rounds",
    "name_source": "screen",
    "i18n_key": "menu.auctionRounds",
    "route": "/auction-rounds",
    "icon_key": "auction_rounds",
    "order": 71,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Auction",
    "resource_key": "cm_mandi_auction_policies.menu",
    "menu_name": "Mandi Auction Policies",
    "name_source": "screen",
    "i18n_key": "menu.auctionPolicies",
    "route": "/auction-policies",
    "icon_key": "auction_policies",
    "order": 72,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Auction",
    "resource_key": "auction_sessions.menu",
    "menu_name": "Auction Sessions",
    "name_source": "screen",
    "i18n_key": "menu.auctionSessions",
    "route": "/auction-sessions",
    "icon_key": "auction_sessions",
    "order": 80,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Auction",
    "resource_key": "auction_lots.menu",
    "menu_name": "Auction Lots",
    "name_source": "screen",
    "i18n_key": "menu.auctionLots",
    "route": "/auction-lots",
    "icon_key": "auction_lots",
    "order": 81,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Auction",
    "resource_key": "auction_results.menu",
    "menu_name": "Auction Results",
    "name_source": "screen",
    "i18n_key": "menu.auctionResults",
    "route": "/auction-results",
    "icon_key": "auction_results",
    "order": 82,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Dashboard",
    "resource_key": "dashboard.menu",
    "menu_name": "Dashboard",
    "name_source": "screen",
    "i18n_key": "menu.dashboard",
    "route": "/dashboard",
    "icon_key": "dashboard",
    "order": 10,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "stall_fees.menu",
    "menu_name": "Stall Fees",
    "name_source": "screen",
    "i18n_key": "screen.stall_fees.menu",
    "route": "/stall-fees",
    "icon_key": "fees",
    "order": 230,
    "metadata_group": "",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "commodity_fees.menu",
    "menu_name": "Commodity Fees",
    "name_source": "screen",
    "i18n_key": "menu.commodity_fees.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "custom_fees.menu",
    "menu_name": "Custom Fees",
    "name_source": "screen",
    "i18n_key": "menu.custom_fees.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "mandi_payment_settings.menu",
    "menu_name": "Mandi Payment Settings",
    "name_source": "screen",
    "i18n_key": "menu.mandi_payment_settings.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "org_payment_settings.menu",
    "menu_name": "Org Payment Settings",
    "name_source": "screen",
    "i18n_key": "menu.org_payment_settings.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "payment_models.menu",
    "menu_name": "Payment Models",
    "name_source": "screen",
    "i18n_key": "menu.payment_models.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "payment_modes.menu",
    "menu_name": "Payment Modes",
    "name_source": "screen",
    "i18n_key": "menu.payment_modes.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "payments_log.menu",
    "menu_name": "Payments Log",
    "name_source": "screen",
    "i18n_key": "menu.payments_log.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "role_custom_fees.menu",
    "menu_name": "Role Custom Fees",
    "name_source": "screen",
    "i18n_key": "menu.role_custom_fees.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "settlements.menu",
    "menu_name": "Settlements",
    "name_source": "screen",
    "i18n_key": "menu.settlements.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "subscription_invoices.menu",
    "menu_name": "Subscription Invoices",
    "name_source": "screen",
    "i18n_key": "menu.subscription_invoices.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Finance",
    "resource_key": "subscriptions.menu",
    "menu_name": "Subscriptions",
    "name_source": "screen",
    "i18n_key": "menu.subscriptions.menu",
    "route": "",
    "icon_key": "",
    "order": null,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_entry_reasons_masters.menu",
    "menu_name": "Gate Entry Reasons",
    "name_source": "screen",
    "i18n_key": "menu.gateEntryReasons",
    "route": "/gate-entry-reasons",
    "icon_key": "gate_entry_reasons",
    "order": 90,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "cm_gate_devices.menu",
    "menu_name": "Gate Devices",
    "name_source": "screen",
    "i18n_key": "menu.gateDevices",
    "route": "/gate-devices",
    "icon_key": "gate_devices",
    "order": 92,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_device_configs.menu",
    "menu_name": "Gate Device Configs",
    "name_source": "screen",
    "i18n_key": "menu.gateDeviceConfigs",
    "route": "/gate-device-configs",
    "icon_key": "gate_device_configs",
    "order": 93,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_pass_tokens.view",
    "menu_name": "Gate Tokens",
    "name_source": "screen",
    "i18n_key": "menu.gateTokens",
    "route": "/gate-tokens",
    "icon_key": "gate_tokens",
    "order": 100,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "weighment_tickets.view",
    "menu_name": "Weighment Tickets",
    "name_source": "screen",
    "i18n_key": "menu.weighmentTickets",
    "route": "/weighment-tickets",
    "icon_key": "weighment_tickets",
    "order": 101,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_movements_log.view",
    "menu_name": "Gate Movements",
    "name_source": "screen",
    "i18n_key": "menu.gateMovements",
    "route": "/gate-movements",
    "icon_key": "gate_movements",
    "order": 102,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_entry_tokens.menu",
    "menu_name": "Gate Entry Tokens",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/gate-entry-tokens",
    "icon_key": "QrCode",
    "order": 200,
    "metadata_group": "",
    "is_active": "Y"
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_vehicle_types_masters.menu",
    "menu_name": "Vehicle Types",
    "name_source": "label",
    "i18n_key": "menu.gate_vehicle_types",
    "route": "/gate/vehicle-types",
    "icon_key": "vehicle",
    "order": 220,
    "metadata_group": "gate_yard_sidebar",
    "is_active": true
  },
  {
    "category": "Gate & Yard",
    "resource_key": "gate_devices.menu",
    "menu_name": "Gate Devices",
    "name_source": "screen",
    "i18n_key": "menu.gate_devices",
    "route": "/gate/devices",
    "icon_key": "device",
    "order": 310,
    "metadata_group": "gate_yard",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandis.menu",
    "menu_name": "Mandis",
    "name_source": "screen",
    "i18n_key": "menu.mandis",
    "route": "/mandis",
    "icon_key": "mandi",
    "order": 50,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_facilities.menu",
    "menu_name": "Mandi Facilities",
    "name_source": "screen",
    "i18n_key": "menu.mandiFacilitiesMasters",
    "route": "/mandi-facilities",
    "icon_key": "mandi_facilities",
    "order": 62,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_gates.menu",
    "menu_name": "Mandi Gates",
    "name_source": "screen",
    "i18n_key": "menu.mandiGates",
    "route": "/mandi-gates",
    "icon_key": "mandi_gates",
    "order": 63,
    "metadata_group": "main_sidebar",
    "is_active": "Y"
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_hours.menu",
    "menu_name": "Mandi Hours Templates",
    "name_source": "screen",
    "i18n_key": "menu.mandiHoursTemplates",
    "route": "/mandi-hours-templates",
    "icon_key": "mandi_hours",
    "order": 64,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_coverage.menu",
    "menu_name": "Mandi Coverage",
    "name_source": "screen",
    "i18n_key": "menu.mandi_coverage",
    "route": "/mandi-coverage",
    "icon_key": "mandi_coverage",
    "order": 80,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_prices.menu",
    "menu_name": "Mandi Prices",
    "name_source": "screen",
    "i18n_key": "menu.mandi_prices",
    "route": "/mandi-prices",
    "icon_key": "mandi_prices",
    "order": 90,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_associations.menu",
    "menu_name": "Mandi Associations",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/mandi-associations",
    "icon_key": "Link",
    "order": 220,
    "metadata_group": "",
    "is_active": "Y"
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_price_policies.menu",
    "menu_name": "Mandi Price Policies",
    "name_source": "screen",
    "i18n_key": "",
    "route": "/mandi-price-policies",
    "icon_key": "",
    "order": 410,
    "metadata_group": "",
    "is_active": true
  },
  {
    "category": "Mandi Setup",
    "resource_key": "mandi_settings.menu",
    "menu_name": "Mandi Settings",
    "name_source": "screen",
    "i18n_key": "",
    "route": "/mandi-settings",
    "icon_key": "",
    "order": 420,
    "metadata_group": "",
    "is_active": true
  },
  {
    "category": "Masters",
    "resource_key": "commodities_masters.menu",
    "menu_name": "Commodities",
    "name_source": "screen",
    "i18n_key": "",
    "route": "/masters/commodities",
    "icon_key": "commodities",
    "order": 310,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Masters",
    "resource_key": "commodity_products_masters.menu",
    "menu_name": "Commodity Products",
    "name_source": "screen",
    "i18n_key": "",
    "route": "/masters/commodity-products",
    "icon_key": "products",
    "order": 320,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Masters",
    "resource_key": "mandi_commodity_products_masters.menu",
    "menu_name": "Mandi Products",
    "name_source": "screen",
    "i18n_key": "",
    "route": "/masters/mandi-products",
    "icon_key": "mandi_products",
    "order": 330,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Operations",
    "resource_key": "pre_market_listings.menu",
    "menu_name": "Pre-Market Listings",
    "name_source": "screen",
    "i18n_key": "screen.pre_market_listings.menu",
    "route": "/pre-market-listings",
    "icon_key": "pre_market",
    "order": 210,
    "metadata_group": "",
    "is_active": true
  },
  {
    "category": "Operations",
    "resource_key": "transport_intents.menu",
    "menu_name": "Transport Intents",
    "name_source": "screen",
    "i18n_key": "screen.transport_intents.menu",
    "route": "/transport-intents",
    "icon_key": "transport",
    "order": 220,
    "metadata_group": "",
    "is_active": true
  },
  {
    "category": "Operations",
    "resource_key": "market_prices.menu",
    "menu_name": "Market Prices",
    "name_source": "screen",
    "i18n_key": "screen.market_prices.menu",
    "route": "/market-prices",
    "icon_key": "prices",
    "order": 240,
    "metadata_group": "",
    "is_active": true
  },
  {
    "category": "Organisation & Access",
    "resource_key": "organisations.menu",
    "menu_name": "Organisations",
    "name_source": "screen",
    "i18n_key": "menu.organisations",
    "route": "/orgs",
    "icon_key": "org",
    "order": 20,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Organisation & Access",
    "resource_key": "admin_users.menu",
    "menu_name": "Admin Users",
    "name_source": "screen",
    "i18n_key": "menu.admin_users",
    "route": "/admin-users",
    "icon_key": "admin_users",
    "order": 30,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Organisation & Access",
    "resource_key": "org_mandi_mappings.menu",
    "menu_name": "Org\u2013Mandi Mappings",
    "name_source": "screen",
    "i18n_key": "menu.orgMandi",
    "route": "/org-mandi",
    "icon_key": "org_mandi",
    "order": 40,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Registry",
    "resource_key": "trader_approvals.menu",
    "menu_name": "Trader Approvals",
    "name_source": "screen",
    "i18n_key": "menu.trader_approvals",
    "route": "/trader-approvals",
    "icon_key": "trader_approvals",
    "order": 60,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Registry",
    "resource_key": "traders.menu",
    "menu_name": "Traders Registry",
    "name_source": "screen",
    "i18n_key": "menu.traders",
    "route": "/traders",
    "icon_key": "traders",
    "order": 121,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Registry",
    "resource_key": "farmers.menu",
    "menu_name": "Farmers Registry",
    "name_source": "screen",
    "i18n_key": "menu.farmers",
    "route": "/farmer-approvals",
    "icon_key": "farmers",
    "order": 122,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "Reports",
    "resource_key": "reports.menu",
    "menu_name": "Reports",
    "name_source": "screen",
    "i18n_key": "menu.reports",
    "route": "/reports",
    "icon_key": "reports",
    "order": 70,
    "metadata_group": "main_sidebar",
    "is_active": true
  },
  {
    "category": "System",
    "resource_key": "system_security.menu",
    "menu_name": "System Security",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/security",
    "icon_key": "security",
    "order": 100,
    "metadata_group": "main_sidebar",
    "is_active": "Y"
  },
  {
    "category": "System",
    "resource_key": "security_switches.menu",
    "menu_name": "Security Switches",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/security/switches",
    "icon_key": "toggle",
    "order": 110,
    "metadata_group": "main_sidebar",
    "is_active": "Y"
  },
  {
    "category": "System",
    "resource_key": "user_roles.menu",
    "menu_name": "User Role Manager",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/user-role-manager",
    "icon_key": "",
    "order": 880,
    "metadata_group": "System",
    "is_active": true
  },
  {
    "category": "System",
    "resource_key": "resource_registry.menu",
    "menu_name": "Resource Registry",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/resource-registry",
    "icon_key": "",
    "order": 890,
    "metadata_group": "System",
    "is_active": true
  },
  {
    "category": "System",
    "resource_key": "security_2fa.menu",
    "menu_name": "2FA Security",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/security/2fa",
    "icon_key": "",
    "order": 895,
    "metadata_group": "System",
    "is_active": true
  },
  {
    "category": "System",
    "resource_key": "stepup_policy.menu",
    "menu_name": "Step-up Policies",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/security/stepup-policies",
    "icon_key": "",
    "order": 897,
    "metadata_group": "System",
    "is_active": true
  },
  {
    "category": "System",
    "resource_key": "mobile_dashboard.menu",
    "menu_name": "Mobile Dashboard",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/mobile-dashboard",
    "icon_key": "Dashboard",
    "order": 900,
    "metadata_group": "",
    "is_active": "Y"
  },
  {
    "category": "System",
    "resource_key": "role_policies.menu",
    "menu_name": "Role Policy Manager",
    "name_source": "label_i18n.en",
    "i18n_key": "",
    "route": "/system/role-policy-manager",
    "icon_key": "",
    "order": 900,
    "metadata_group": "System",
    "is_active": "Y"
  }
];
