export const CM_COLORS = {
  primary: "#55632C",
  primarySoft: "#6E7C3A",
  primaryDeep: "#38451D",
  accent: "#C57A35",
  accentSoft: "#E3B278",
  background: "#FFFFFF",
  backgroundElevated: "#F7F8F4",
  surface: "#FFFFFF",
  surfaceMuted: "#F4F6F0",
  text: "#1F241A",
  textMuted: "#596052",
  textSubtle: "#7D8577",
  border: "#E6E9E1",
  borderStrong: "#D5DACF",
  success: "#3E7B4B",
  warning: "#B97822",
  error: "#B93A3A",
  info: "#3F6F8F",
  sidebar: "#F6F8F3",
  sidebarElevated: "#FFFFFF",
  sidebarText: "#24301D",
  sidebarMuted: "#66715E",
  sidebarBorder: "#E2E7DC",
  sidebarActive: "#E8EEE0",
  loginBrand: "#263019",
  loginBrandElevated: "#303B20",
  loginBrandText: "#FFFFFF",
  loginBrandMuted: "#E5E9DE",
  loginBrandBorder: "rgba(255,255,255,0.14)",
  loginBrandActive: "rgba(255,255,255,0.14)",
  overlay: "rgba(27,31,20,0.56)",
} as const;

export const CM_SHELL = {
  sidebarWidth: 284,
  sidebarCollapsedWidth: 84,
  headerHeight: 72,
  contentMaxWidth: 1800,
  pageGutterDesktop: 28,
  pageGutterTablet: 20,
  pageGutterMobile: 14,
} as const;

export const CM_RADII = {
  xs: 8,
  sm: 10,
  md: 14,
  lg: 18,
  xl: 24,
  pill: 999,
} as const;

export const CM_SHADOWS = {
  card: "0 8px 28px rgba(44, 48, 34, 0.07)",
  elevated: "0 14px 42px rgba(44, 48, 34, 0.10)",
  floating: "0 20px 56px rgba(25, 31, 18, 0.16)",
} as const;

export const CM_THEME = {
  colors: CM_COLORS,
  shell: CM_SHELL,
  radii: CM_RADII,
  shadows: CM_SHADOWS,
} as const;

const cssVariables: Record<string, string> = {
  "--cm-primary": CM_COLORS.primary,
  "--cm-primary-dark": CM_COLORS.primaryDeep,
  "--cm-primary-soft": CM_COLORS.primarySoft,
  "--cm-primary-deep": CM_COLORS.primaryDeep,
  "--cm-primary-ink": CM_COLORS.primaryDeep,
  "--cm-gold": CM_COLORS.accent,
  "--cm-secondary": CM_COLORS.accent,
  "--cm-secondary-dark": CM_COLORS.accent,
  "--cm-secondary-soft": CM_COLORS.accentSoft,
  "--cm-accent": CM_COLORS.accent,
  "--cm-accent-soft": CM_COLORS.accentSoft,
  "--cm-bg": CM_COLORS.background,
  "--cm-bg-soft": CM_COLORS.backgroundElevated,
  "--cm-bg-elevated": CM_COLORS.backgroundElevated,
  "--cm-surface": CM_COLORS.surface,
  "--cm-surface-muted": CM_COLORS.surfaceMuted,
  "--cm-text": CM_COLORS.text,
  "--cm-text-soft": CM_COLORS.textMuted,
  "--cm-muted": CM_COLORS.textMuted,
  "--cm-text-muted": CM_COLORS.textMuted,
  "--cm-text-subtle": CM_COLORS.textSubtle,
  "--cm-border": CM_COLORS.border,
  "--cm-border-strong": CM_COLORS.borderStrong,
  "--cm-success": CM_COLORS.success,
  "--cm-success-soft": CM_COLORS.backgroundElevated,
  "--cm-warning": CM_COLORS.warning,
  "--cm-warning-soft": CM_COLORS.backgroundElevated,
  "--cm-error": CM_COLORS.error,
  "--cm-danger": CM_COLORS.error,
  "--cm-danger-soft": CM_COLORS.backgroundElevated,
  "--cm-info": CM_COLORS.info,
  "--cm-info-soft": CM_COLORS.backgroundElevated,
  "--cm-sidebar": CM_COLORS.sidebar,
  "--cm-sidebar-elevated": CM_COLORS.sidebarElevated,
  "--cm-sidebar-text": CM_COLORS.sidebarText,
  "--cm-sidebar-muted": CM_COLORS.sidebarMuted,
  "--cm-sidebar-border": CM_COLORS.sidebarBorder,
  "--cm-sidebar-active": CM_COLORS.sidebarActive,
  "--cm-overlay": CM_COLORS.overlay,
  "--cm-login-brand": CM_COLORS.loginBrand,
  "--cm-login-brand-elevated": CM_COLORS.loginBrandElevated,
  "--cm-login-brand-text": CM_COLORS.loginBrandText,
  "--cm-login-brand-muted": CM_COLORS.loginBrandMuted,
  "--cm-login-brand-border": CM_COLORS.loginBrandBorder,
  "--cm-login-brand-active": CM_COLORS.loginBrandActive,
  "--cm-sidebar-width": `${CM_SHELL.sidebarWidth}px`,
  "--cm-sidebar-collapsed-width": `${CM_SHELL.sidebarCollapsedWidth}px`,
  "--cm-header-height": `${CM_SHELL.headerHeight}px`,
  "--cm-content-max": `${CM_SHELL.contentMaxWidth}px`,
  "--cm-page-max": `${CM_SHELL.contentMaxWidth}px`,
  "--cm-shell-gap": "clamp(12px, 1.2vw, 22px)",
  "--cm-radius-card": `${CM_RADII.md}px`,
  "--cm-radius-sm": `${CM_RADII.sm}px`,
  "--cm-radius-md": `${CM_RADII.md}px`,
  "--cm-radius-lg": `${CM_RADII.lg}px`,
  "--cm-radius-xl": `${CM_RADII.xl}px`,
  "--cm-button-radius": `${CM_RADII.sm}px`,
  "--cm-chip-radius": `${CM_RADII.xs}px`,
  "--cm-control-radius": `${CM_RADII.sm}px`,
  "--cm-shadow-sm": CM_SHADOWS.card,
  "--cm-shadow-md": CM_SHADOWS.elevated,
  "--cm-shadow-lg": CM_SHADOWS.floating,
  "--cm-shadow-card": CM_SHADOWS.card,
  "--cm-shadow-elevated": CM_SHADOWS.elevated,
  "--cm-shadow-floating": CM_SHADOWS.floating,
};

export const applyCmThemeVariables = (target?: HTMLElement | null) => {
  if (typeof document === "undefined") return;
  const root = target || document.documentElement;
  Object.entries(cssVariables).forEach(([name, value]) => root.style.setProperty(name, value));
};
